### ISSUE TITLE
Wrong metadata for "Chevelle - Sci-Fi Crimes"

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk#469] opened 2016-03-15 19:00 UTC
it is sort of similar to issue #378 but this one is 100% reproducible and is a separate issue.

Tomahawk always, 100% of times shows wrong tracklist for this release.
It shows tracklist from "Sci-Fi Crimes EP"

**Comment by muesli** [comment] 2016-03-27 16:55
Dupe of #443.

**Closed by muesli** 2016-03-27 16:55 UTC
