### ISSUE TITLE
Genre.h not found

### ISSUE THREAD

**Issue by irwisch** [tomahawk-player/tomahawk#340] opened 2015-11-21 15:04 UTC
"In file included from tomahawk/src/libtomahawk/playlist/dynamic/echonest/EchonestGenerator.cpp:20:0:
tomahawk/src/libtomahawk/playlist/dynamic/echonest/EchonestGenerator.h:37:28: fatal error: echonest/Genre.h: No such file or directory
compilation terminated."

Some ideas?

**Comment by dschmidt** [comment] 2015-11-21 15:11
Try updating libechonest

**Comment by dschmidt** [comment] 2015-11-21 15:12
You need 2.3.0 or something iirc

**Comment by irwisch** [comment] 2015-11-21 16:35
https://packages.debian.org/stretch/libechonest-dbg

Suggestions how to do this on debian? In the repos there's only 2.1...

**Comment by justin-time** [comment] 2015-11-22 10:56
You could write a comment on this bugreport https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766594 to show the maintainer that he should update libechonest as soon as possible…

**Comment by justin-time** [comment] 2015-12-21 08:43
A working libechonest2.3 package is now in debian sid:
https://tracker.debian.org/pkg/libechonest
It will be migrated into debian testing/stretch in the next days.

**Comment by goncalor** [comment] 2016-01-14 01:09
Same problem here. I'm compiling on Debian Jessie. The available version for `libechonest` is 2.1.0.

**Comment by dschmidt** [comment] 2016-01-15 01:12
Thanks everyone for posting help!

Closing this as it's not a bug (except for maybe a missing/not working version check for libechonest).

**Closed by dschmidt** 2016-01-15 01:12 UTC
Labels: build system
