### ISSUE TITLE
Bad album content shown (Peter Gabriel)

### ISSUE THREAD

**Issue by Jacajack** [tomahawk-player/tomahawk#476] opened 2016-03-19 00:04 UTC
I recently started using Tomahawk as my music player, and then I realized that even though my music collection is correctly tagged, it's shown incorrectly in Tomahawk.
I discovered that one of my album contains tracks from other album.

I think it's sorta similar to issues https://github.com/tomahawk-player/tomahawk/issues/469 and https://github.com/tomahawk-player/tomahawk/issues/378

As shown below, `Peter Gabriel (Car)` contains songs from `Peter Gabriel (Melt)`.

![image](https://cloud.githubusercontent.com/assets/6173262/13894804/55121010-ed6c-11e5-961a-4c9a8e82960f.png)

As you can clearly see, exactly same tracks appear here:

![image](https://cloud.githubusercontent.com/assets/6173262/13894870/f67c91a0-ed6c-11e5-8fa0-f699be4f691c.png)

This is how `Peter Gabriel (Car)` tracks are tagged (using Easytag):

![image](https://cloud.githubusercontent.com/assets/6173262/13894901/403f7fa0-ed6d-11e5-9b4b-f0b4353b6038.png)

*I believe everything is fine here, tell me if you see that something is wrong*

Tracks from `Peter Gabriel (Car)` cannot be accessed by searching too.
I can play some of them though, by finding similar tracks on other albums, like here:
![image](https://cloud.githubusercontent.com/assets/6173262/13894982/45fa5694-ed6e-11e5-9844-48cd97f32ad9.png)

When song is played, album name and cover are displayed correctly:
![image](https://cloud.githubusercontent.com/assets/6173262/13894990/5a038052-ed6e-11e5-9e64-b1e24db6569f.png)

**EDIT:** `Peter Gabriel - Hit (Disc 1)` track listing also contains songs from `Peter Gabriel (Melt)`

My only enabled plugin is Hatchet.

Thank you in advance :)

**Comment by theli-ua** [comment] 2016-03-27 16:51
> I think it's sorta similar to issues #469

Not similar, this is the same issue. Its because tomahawk gets track listing from musicbrainz and there all albums are not titled "Peter Gabriel (Car)" but just "Peter Gabriel" with "Car" as disambiguation

**Comment by muesli** [comment] 2016-03-27 16:56
Dupe of #443.

**Closed by muesli** 2016-03-27 16:56 UTC
