### ISSUE TITLE
No way to see release date in Artists' albums list

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk#409] opened 2016-01-22 19:09 UTC

**Comment by muesli** [comment] 2016-02-28 23:17
Dupe of #454 - even tho older, closing this one.

**Closed by muesli** 2016-02-28 23:17 UTC

**Comment by theli-ua** [comment] 2016-02-28 23:18
:(
I swear to was trying to find issue about this but failed :(

**Comment by muesli** [comment] 2016-02-29 00:11
Haha, no worries :)
