### ISSUE TITLE
Tomahawk didn't import all of my MP3 files

### ISSUE THREAD

**Issue by davidrhoderick** [tomahawk-player/tomahawk#360] opened 2015-12-11 16:43 UTC
Hello forum,

I recently gave up on iTunes because of their debacle with iCloud Music, which made it so that I can't listen to my purchased and locally stored music without an iCloud Music subscription.  Therefore I went to DoubleTwist, which didn't have great performance, and tried others until landing on Tomahawk, which looks great on the surface.

It imported most of my collection without much issue, but with several album, it didn't import the files at all.  Most of my library has near full ID3 tags and they have at least the Tomahawk minimum.  I have one specific album that refuses to load in Tomahawk even though it has everything including album artwork in the tags.  As you can see by the screenshot below, this DJ Spooky album has totally incorrect data, a bunch of piano music instead of what his album is.  What is going on and how do I fix this?

![screenshot 2015-12-11 17 42 09](https://cloud.githubusercontent.com/assets/2300366/11749519/8e7aa852-a02e-11e5-8f6c-37eb435f1dd8.png)

Please let me know if you need more information.  My music library is about 10200 songs so the log file is a bit huge but I can send it if necessary.

**Comment by muesli** [comment] 2015-12-11 17:07
Are those tracks showing up fine in the Songs tab of your collection? I suppose it's finding your tracks just finding, but finds different metadata for the album on musicbrainz, which it then tries to resolve against.

**Comment by davidrhoderick** [comment] 2015-12-11 17:28
Oh wow, what a catch!  Yes, the album works on the "Songs" tab.  It looks find on musicbrainz, actually, the link is https://musicbrainz.org/release/8a7ab01b-c932-4100-8655-cd7c7c45d612.  Any idea why it is showing up incorrectly?

**Comment by muesli** [comment] 2016-02-22 19:13
Yes, see the explanation I gave on #443. Closing this as a dupe of #443 - even tho your ticket is older (sorry). Expect a fix in 0.9!

**Closed by muesli** 2016-02-22 19:13 UTC
