### ISSUE TITLE
UI problems when using dark xfce skin

### ISSUE THREAD

**Issue by mrmaffen** [tomahawk-player/tomahawk#457] opened 2016-02-28 17:34 UTC
Minor issues:
- Back and forward button (top left corner) are too dark
- Wrench icon (top right corner) is too dark

Major issues:
- "Show more" button below top hits and top albums on artist page doesn't show up at all. This is because my dark skin uses white text. Since the background is hard-coded to white the text should also be hard-coded to grey.

![bildschirmfoto vom 2016-02-28 18 22 35](https://cloud.githubusercontent.com/assets/1526877/13380724/bdccb40c-de49-11e5-8784-b238bc91ead0.png)

**Comment by muesli** [comment] 2016-02-28 20:52
Linked to/Dupe of #432.

**Closed by muesli** 2016-02-28 20:52 UTC
