### ISSUE TITLE
Locally stored albums fail to play "This playlist is currently empty"

### ISSUE THREAD

**Issue by scheidm** [tomahawk-player/tomahawk#428] opened 2016-02-05 14:07 UTC
After downloading the app, hooking up bandcamp, soundcloud, google play and my local iTunes collection, I've been having issues both finding albums in search, and more importantly, playing albums directly from my collection.

if I click on an artist, it will show their albums listed correctly, but many of them are randomly missing their cd images. I click play, nothing happens, I click on the album name and am brought to a blank screen with a single track box, no details and the error "This playlist is currently empty" displays on screen.

Issue occurring on Mac OS X

**Comment by muesli** [comment] 2016-02-22 19:10
Dupe of #443.

**Closed by muesli** 2016-02-22 19:10 UTC
