### ISSUE TITLE
Player freezes/crashes when attempting to filter in Ampache cloud (Win7)

### ISSUE THREAD

**Issue by Liarra** [tomahawk-player/tomahawk#353] opened 2015-12-07 15:00 UTC
Windows 7 Enterprise, 64 bit
Tomahawk is downloaded from https://www.tomahawk-player.org/

### How to reproduce:
1. Add Ampache resource, preferably the one with lots of music.
2. Click Ampache tab under "Cloud collections"
3. Type something in "Filter" field on top right.

### Expected behaviour:
The player displays matching items.

### Actual behaviour:
The player crashes.
OR
The player freezes.
OR
The player displays nothing even when the substring is present in several items.

**Comment by dschmidt** [comment] 2016-02-21 11:22
Cannot reproduce. There have been a bunch of changes to this kind of collections lately, so it's possible it has been fixed by those. If not, we can reopen. Just let us know if it's still happening for you in latest nightly: http://download.tomahawk-player.org/nightly/windows/tomahawk-latest.exe

**Closed by dschmidt** 2016-02-21 11:22 UTC
