### ISSUE TITLE
"Sorry, couldn't find any playable tracks"

### ISSUE THREAD

**Issue by HinkMyDinkD00d** [tomahawk-player/tomahawk#449] opened 2016-02-22 05:14 UTC
Several albums (Mostly video game soundtracks) refuse to play in the "Albums" column of the Collection tab. However, tracks can be played individually in the "Songs" column without issue.
Affected albums' tracks all have the same Album tag and unique Artist / Title tags.
Tracks also have varying bitrates, if it matters.

**Comment by muesli** [comment] 2016-02-22 19:11
Dupe of #443.

**Closed by muesli** 2016-02-22 19:11 UTC

**Comment by HinkMyDinkD00d** [comment] 2016-02-23 00:07
Ah ok
Thanks for linking to that other issue
Glad to know that it's being resolved in the next release
