### ISSUE TITLE
album detection is prone to disasters

### ISSUE THREAD

**Issue by ootada** [tomahawk-player/tomahawk#468] opened 2016-03-15 16:18 UTC
examples (all local files, tagged correctly):

1. bunch of different flac albums detects same track names for all the albums that has nothing common with the actual tracks in the directory and i do not even have tracks named like that anywhere else it seems.

2. mp3 album collection - discography single artist: shows correct artist and album name in the list, when clicking on the album name you get different album name displayed with different tracks from same artist. several cases of this behavior.

Possibly add ability to easily report wrong detection?

**Comment by muesli** [comment] 2016-03-15 17:43
Dupe of #443. Fix coming up in 0.9.

**Closed by muesli** 2016-03-15 17:43 UTC
